apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: minikube
  labels:
    run: ftps
spec:
  type: LoadBalancer
  selector:
    run: ftps
  ports:
  - name: ftps
    port: 21
    protocol: TCP
  - name: pasv
    port: 40000
    protocol: TCP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ftps
  labels:
    run: ftps
spec:
  serviceName: ftps
  replicas: 1
  selector:
    matchLabels:
      run: ftps
  template:
    metadata:
      labels:
        run: ftps
    spec:
      containers:
      - name: ftps
        image: ftps_img
        imagePullPolicy: Never
        ports:
        - containerPort: 21
          name: ftps
        - containerPort: 40000
          name: pasv
