apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: minikube
  labels:
    run: ftps
spec:
  type: LoadBalancer
  selector:
    run: ftps
  ports:
  - name: ftps
    port: 21
    protocol: TCP
  - name: pasv0
    port: 20000
    protocol: TCP
  - name: pasv1
    port: 20001
    protocol: TCP
  - name: pasv2
    port: 20002
    protocol: TCP
  - name: pasv3
    port: 20003
    protocol: TCP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ftps
  labels:
    run: ftps
spec:
  serviceName: ftps
  replicas: 1
  selector:
    matchLabels:
      run: ftps
  template:
    metadata:
      labels:
        run: ftps
    spec:
      containers:
      - name: ftps
        image: ftps_img
        imagePullPolicy: Never
        ports:
        - containerPort: 21
          name: ftps
        - containerPort: 40000
          name: pasv
        livenessProbe:
          exec:
            command:
            - sh
            - /check.sh
          initialDelaySeconds: 10
          periodSeconds: 5
