apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    run: grafana
  annotations:
    metallb.universe.tf/allow-shared-ip: minikube
spec:
  type: LoadBalancer
  selector:
    run: grafana
  ports:
  - port: 3000
    protocol: TCP
    name: http
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grafana
  labels:
    run: grafana
spec:
  serviceName: grafana
  replicas: 1
  selector:
    matchLabels:
      run: grafana
  template:
    metadata:
      labels:
        run: grafana
    spec:
      containers:
      - name: grafana
        image: grafana_img
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
