apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: minikube
  labels:
    run: wordpress
spec:
  type: LoadBalancer
  ports:
  - name: https
    port: 5050
    targetPort: 5050
  selector:
    run: wordpress
